nodes: 1
tasks_per_node: 1
tag: k400-16x8x3
eval_name: video_classification_frozen
resume_checkpoint: false
data:
  dataset_train: /home/your-user/ML-datasets/video_datasets/k400/k400_train_file_index.csv
  dataset_val: /home/your-user/ML-datasets/video_datasets/k400/k400_val_file_index.csv
  dataset_type: VideoDataset
  num_classes: 400
  frames_per_clip: 16
  num_segments: 8
  num_views_per_segment: 3
  frame_step: 4
optimization:
  attend_across_segments: true
  num_epochs: 3
  resolution: 224
  batch_size: 4
  weight_decay: 0.01
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
pretrain:
  model_name: vit_tiny
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /home/your-user/ML-models/nano-jepa-checkpoints/
  checkpoint: jepa-latest.pth.tar
  write_tag: nano-jepa-eval
logging:
  folder: /home/your-user/ML-logging/nano-jepa-logging
